#!/bin/bash
while read file; do
    echo $file >> file.txt
done
head -n 20 < file.txt

# In this challenge, we practice using the head command to display the first  lines of a text file.
# Display the first 20 lines of an input file.